export interface PracticeCommand {
  id: string;
  command: string;
  title: string;
  category: PracticeCategory;
  categoryTitle: string;
  description: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  flags?: { flag: string; desc: string }[];
  tags: string[];
  devopsScenario?: string;
  exampleOutput?: string;
}

export type PracticeCategory =
  | 'fundamentals'
  | 'files'
  | 'permissions'
  | 'processes'
  | 'networking'
  | 'text'
  | 'disk'
  | 'bash'
  | 'devops';

export interface CategoryMeta {
  id: PracticeCategory;
  title: string;
  description: string;
  badge: string;
}

export const PRACTICE_CATEGORIES: CategoryMeta[] = [
  { id: 'fundamentals', title: 'Linux Fundamentals', description: 'Terminal navigation, system identity, and environment variables', badge: 'Terminal' },
  { id: 'files', title: 'File & Directory Ops', description: 'Creation, recursive searching, moves, copies, and file trees', badge: 'Files' },
  { id: 'permissions', title: 'Permissions & Security', description: 'Octal modes, least-privilege security, and ownership', badge: 'Security' },
  { id: 'processes', title: 'Processes & Lifecycle', description: 'Process trees, PID signals, resource inspection, and daemons', badge: 'Processes' },
  { id: 'networking', title: 'Cloud Networking', description: 'Socket states, port bindings, IP config, and HTTP requests', badge: 'Network' },
  { id: 'text', title: 'Log Analysis & Text Processing', description: 'grep, awk, sed, stream pipelines, sorting, and regex filtering', badge: 'Logs & Streams' },
  { id: 'disk', title: 'Storage & Hardware Stats', description: 'Disk usage, memory consumption, inode counts, and system metrics', badge: 'Storage' },
  { id: 'bash', title: 'Shell Scripting & Pipelines', description: 'Standard I/O redirects, exit code checks, and automated loops', badge: 'Scripting' },
  { id: 'devops', title: 'DevOps & Production Incidents', description: 'Service healthchecks, log triage, tar archives, and socket probing', badge: 'DevOps' },
];

export const PRACTICE_COMMANDS: PracticeCommand[] = [
  // 1. Fundamentals
  {
    id: 'fund-pwd',
    command: 'pwd',
    title: 'Print Working Directory',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Displays the absolute filesystem path of the current working directory.',
    difficulty: 'Beginner',
    tags: ['navigation', 'path', 'fundamentals'],
    devopsScenario: 'Verifying script execution context and confirming current directory in deployment pipelines.',
  },
  {
    id: 'fund-ls-la',
    command: 'ls -lah',
    title: 'List Files with Metadata & Hidden Entries',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Lists all directory contents including hidden dotfiles, with human-readable file sizes and permissions.',
    difficulty: 'Beginner',
    flags: [
      { flag: '-l', desc: 'Long listing format showing permissions, owner, and timestamp' },
      { flag: '-a', desc: 'Include hidden files (starting with .)' },
      { flag: '-h', desc: 'Human-readable sizes (K, M, G)' },
    ],
    tags: ['navigation', 'files', 'metadata'],
    devopsScenario: 'Inspecting repository root for hidden configuration files like .env, .git, and .bashrc.',
  },
  {
    id: 'fund-cd-home',
    command: 'cd ~',
    title: 'Navigate to Current User Home Directory',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Changes the active working directory to the logged-in user home (/home/sai).',
    difficulty: 'Beginner',
    tags: ['navigation', 'cd', 'home'],
  },
  {
    id: 'fund-cd-back',
    command: 'cd -',
    title: 'Switch to Previous Directory',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Toggles back to the previous working directory before the last cd command.',
    difficulty: 'Beginner',
    tags: ['navigation', 'cd', 'productivity'],
  },
  {
    id: 'fund-whoami',
    command: 'whoami',
    title: 'Display Active User Identity',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Prints the effective username of the currently logged-in shell user.',
    difficulty: 'Beginner',
    tags: ['identity', 'user', 'security'],
    devopsScenario: 'Confirming non-root execution inside containerized deployment runners.',
  },
  {
    id: 'fund-uname-a',
    command: 'uname -a',
    title: 'Inspect Kernel & Architecture Details',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Prints comprehensive system architecture, kernel release, and hostname information.',
    difficulty: 'Beginner',
    flags: [{ flag: '-a', desc: 'Print all system architecture and kernel metadata' }],
    tags: ['system', 'kernel', 'architecture'],
    devopsScenario: 'Checking CPU architecture (x86_64 vs arm64) before pulling native binary releases.',
  },
  {
    id: 'fund-env',
    command: 'env',
    title: 'List Exported Environment Variables',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Displays all globally exported environment variables accessible to child processes.',
    difficulty: 'Beginner',
    tags: ['environment', 'variables', 'config'],
    devopsScenario: 'Debugging missing PATH or microservice database connection parameters in CI/CD.',
  },
  {
    id: 'fund-date',
    command: 'date',
    title: 'Check System Clock & UTC Timestamp',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Outputs the current system date, time, and timezone.',
    difficulty: 'Beginner',
    tags: ['system', 'time', 'ntp'],
    devopsScenario: 'Diagnosing clock drift during distributed database synchronization or TLS handshake failures.',
  },
  {
    id: 'fund-history',
    command: 'history | tail -n 10',
    title: 'View Last 10 Executed Commands',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Displays numbered shell execution history piped to tail to see recent terminal actions.',
    difficulty: 'Beginner',
    tags: ['history', 'shell', 'audit'],
  },
  {
    id: 'fund-tree',
    command: 'tree',
    title: 'Visual Directory Tree Representation',
    category: 'fundamentals',
    categoryTitle: 'Linux Fundamentals',
    description: 'Prints a graphical depth-indentation tree of directories and files in the current folder.',
    difficulty: 'Beginner',
    tags: ['tree', 'filesystem', 'visual'],
  },

  // 2. Files & Directories
  {
    id: 'file-mkdir-p',
    command: 'mkdir -p /home/sai/deployments/releases/v2.4',
    title: 'Create Nested Parent Directories Recursively',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Creates deep nested folder structures without erroring if parents do not exist.',
    difficulty: 'Beginner',
    flags: [{ flag: '-p', desc: 'Make intermediate parent directories as needed without failing' }],
    tags: ['mkdir', 'directories', 'filesystem'],
    devopsScenario: 'Preparing target release directories during zero-downtime blue/green deployment scripts.',
  },
  {
    id: 'file-touch',
    command: 'touch /home/sai/workspace/config.yaml',
    title: 'Create New Empty File or Update Timestamp',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Creates a new empty file if it does not exist, or refreshes the access/modification time.',
    difficulty: 'Beginner',
    tags: ['touch', 'files', 'create'],
  },
  {
    id: 'file-cp-r',
    command: 'cp -r /home/sai/projects/app /home/sai/projects/app_backup',
    title: 'Recursively Copy Entire Application Directory',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Duplicates a full directory tree with all nested files and subfolders.',
    difficulty: 'Intermediate',
    flags: [{ flag: '-r', desc: 'Copy directories recursively' }],
    tags: ['cp', 'backup', 'directories'],
    devopsScenario: 'Creating a fast local snapshot before running database migration scripts.',
  },
  {
    id: 'file-mv',
    command: 'mv /home/sai/projects/temp.txt /home/sai/projects/archive.txt',
    title: 'Rename or Move File to New Location',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Moves or renames files across directories with atomic rename semantics.',
    difficulty: 'Beginner',
    tags: ['mv', 'rename', 'files'],
  },
  {
    id: 'file-rm-rf',
    command: 'rm -rf /tmp/build_cache',
    title: 'Forcefully & Recursively Remove Directory',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Recursively deletes files and folders without prompting for confirmation.',
    difficulty: 'Intermediate',
    flags: [
      { flag: '-r', desc: 'Remove directories and their contents recursively' },
      { flag: '-f', desc: 'Ignore nonexistent files and arguments, never prompt' },
    ],
    tags: ['rm', 'cleanup', 'delete'],
    devopsScenario: 'Purging transient artifact caches after Docker image builds in ephemeral runners.',
  },
  {
    id: 'file-find-name',
    command: 'find /var/log -name "*.log"',
    title: 'Find Files by Wildcard Extension',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Recursively scans filesystem hierarchy to locate all files matching a wildcard pattern.',
    difficulty: 'Intermediate',
    flags: [{ flag: '-name', desc: 'Filter filenames matching case-sensitive shell pattern' }],
    tags: ['find', 'search', 'logs'],
    devopsScenario: 'Locating log files to ingest into Promtail, FluentBit, or AWS CloudWatch agents.',
  },
  {
    id: 'file-find-type',
    command: 'find /home/sai -type f',
    title: 'Find Regular Files Only (Excluding Directories)',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Filters search results to only return regular file nodes.',
    difficulty: 'Beginner',
    flags: [{ flag: '-type f', desc: 'Match regular files only' }],
    tags: ['find', 'filter', 'files'],
  },
  {
    id: 'file-head',
    command: 'head -n 5 /var/log/nginx/access.log',
    title: 'Read Top Lines of a Large File',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Prints the first N lines of a file to stdout without loading the entire file into memory.',
    difficulty: 'Beginner',
    flags: [{ flag: '-n 5', desc: 'Print the first 5 lines' }],
    tags: ['head', 'read', 'logs'],
  },
  {
    id: 'file-tail',
    command: 'tail -n 10 /var/log/nginx/access.log',
    title: 'Inspect Most Recent Lines in Log File',
    category: 'files',
    categoryTitle: 'File & Directory Ops',
    description: 'Outputs the last 10 records written to an active log stream.',
    difficulty: 'Beginner',
    flags: [{ flag: '-n 10', desc: 'Print the last 10 lines' }],
    tags: ['tail', 'logs', 'monitoring'],
    devopsScenario: 'Inspecting latest incoming traffic timestamps during live traffic switchovers.',
  },

  // 3. Permissions & Security
  {
    id: 'perm-chmod-600',
    command: 'chmod 600 /home/sai/.ssh/id_rsa',
    title: 'Secure Private SSH Key Permissions',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Sets read/write for owner only (rw-------). OpenSSH strictly rejects keys with broader permissions.',
    difficulty: 'Intermediate',
    flags: [{ flag: '600', desc: 'Owner: read+write (6), Group: none (0), Others: none (0)' }],
    tags: ['security', 'ssh', 'chmod'],
    devopsScenario: 'Preventing "WARNING: UNPROTECTED PRIVATE KEY FILE!" failures during automated ansible plays.',
  },
  {
    id: 'perm-chmod-755',
    command: 'chmod 755 /home/sai/scripts/healthcheck.sh',
    title: 'Make Script Executable for Owner, Readable by All',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Assigns rwxr-xr-x mode so the owner can read/write/execute and everyone else can read/execute.',
    difficulty: 'Beginner',
    flags: [{ flag: '755', desc: 'Owner: 7 (rwx), Group: 5 (r-x), Others: 5 (r-x)' }],
    tags: ['chmod', 'executable', 'scripts'],
  },
  {
    id: 'perm-chmod-plus-x',
    command: 'chmod +x /home/sai/scripts/worker.py',
    title: 'Add Execute Bit to Script',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Adds executable permission to the file for all classes (user, group, others).',
    difficulty: 'Beginner',
    tags: ['chmod', 'exec', 'scripts'],
  },
  {
    id: 'perm-chown-user',
    command: 'chown sai:sai /home/sai/workspace/config.yaml',
    title: 'Change File Owner and Primary Group',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Reassigns file ownership to user "sai" and group "sai".',
    difficulty: 'Intermediate',
    tags: ['chown', 'ownership', 'security'],
    devopsScenario: 'Fixing root-owned build output files so non-root CI runner processes can access them.',
  },
  {
    id: 'perm-chmod-700',
    command: 'chmod 700 /home/sai/.ssh',
    title: 'Restrict SSH Directory Access to Owner Only',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Sets directory access so only the user can enter and list keys in the folder.',
    difficulty: 'Intermediate',
    tags: ['ssh', 'chmod', 'hardening'],
  },
  {
    id: 'perm-cat-sudoers',
    command: 'cat /etc/sudoers',
    title: 'Inspect Sudo Privileges Configuration',
    category: 'permissions',
    categoryTitle: 'Permissions & Security',
    description: 'Reads system sudoers policy file governing elevated administrative privileges.',
    difficulty: 'Intermediate',
    tags: ['sudo', 'security', 'privileges'],
  },

  // 4. Processes & Lifecycle
  {
    id: 'proc-ps-aux',
    command: 'ps aux',
    title: 'List All Running Processes in System',
    category: 'processes',
    categoryTitle: 'Processes & Lifecycle',
    description: 'Displays a snapshot of current processes with PID, CPU%, MEM%, and command strings.',
    difficulty: 'Beginner',
    flags: [
      { flag: 'a', desc: 'Show processes for all users' },
      { flag: 'u', desc: 'Display user-oriented format with CPU & Memory percentages' },
      { flag: 'x', desc: 'Include processes without a controlling terminal (daemons)' },
    ],
    tags: ['ps', 'processes', 'monitoring'],
    devopsScenario: 'Identifying memory-hungry background worker tasks during incident response.',
  },
  {
    id: 'proc-ps-grep',
    command: 'ps aux | grep nginx',
    title: 'Filter Process List for Nginx Workers',
    category: 'processes',
    categoryTitle: 'Processes & Lifecycle',
    description: 'Pipes the full process table into grep to locate specific service master and worker PIDs.',
    difficulty: 'Intermediate',
    tags: ['ps', 'grep', 'nginx'],
    devopsScenario: 'Confirming if web server master process spawned child worker processes correctly.',
  },
  {
    id: 'proc-kill-9',
    command: 'kill -9 1042',
    title: 'Send SIGKILL to Force Terminate Runaway Process',
    category: 'processes',
    categoryTitle: 'Processes & Lifecycle',
    description: 'Dispatches uncatchable SIGKILL (Signal 9) to abruptly kill PID 1042.',
    difficulty: 'Intermediate',
    flags: [{ flag: '-9', desc: 'SIGKILL: Forces immediate process termination at kernel level' }],
    tags: ['kill', 'signals', 'troubleshooting'],
    devopsScenario: 'Stopping un-responsive worker scripts that fail to respond to standard SIGTERM (Signal 15).',
  },
  {
    id: 'proc-top',
    command: 'top',
    title: 'Live Interactive System Resource & Process Monitor',
    category: 'processes',
    categoryTitle: 'Processes & Lifecycle',
    description: 'Displays dynamic real-time summary of CPU load, memory usage, and top active tasks.',
    difficulty: 'Beginner',
    tags: ['top', 'cpu', 'memory'],
  },
  {
    id: 'proc-uptime',
    command: 'uptime',
    title: 'Check System Uptime & 1/5/15-Min Load Averages',
    category: 'processes',
    categoryTitle: 'Processes & Lifecycle',
    description: 'Prints how long the server has been running, logged-in users, and 1, 5, and 15 minute CPU load averages.',
    difficulty: 'Beginner',
    tags: ['uptime', 'load', 'health'],
    devopsScenario: 'Determining if CPU saturation is a brief transient spike vs sustained system bottleneck.',
  },

  // 5. Cloud Networking
  {
    id: 'net-ss-tulpn',
    command: 'ss -tulpn',
    title: 'Inspect Listening Sockets & Binding Ports',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Displays all active TCP and UDP listening ports with associated process names and PIDs.',
    difficulty: 'Intermediate',
    flags: [
      { flag: '-t', desc: 'Display TCP sockets' },
      { flag: '-u', desc: 'Display UDP sockets' },
      { flag: '-l', desc: 'Show only listening sockets' },
      { flag: '-p', desc: 'Show process using socket' },
      { flag: '-n', desc: 'Do not resolve service names (show numeric port e.g. 80 instead of http)' },
    ],
    tags: ['ss', 'ports', 'networking'],
    devopsScenario: 'Diagnosing "Port already in use" errors during container or web service startups.',
  },
  {
    id: 'net-ip-a',
    command: 'ip a',
    title: 'Inspect Network Interfaces & IP Addresses',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Lists all network interfaces (eth0, lo) and their configured IPv4/IPv6 CIDR addresses.',
    difficulty: 'Beginner',
    flags: [{ flag: 'a', desc: 'Shorthand for address: show protocol addresses' }],
    tags: ['ip', 'interfaces', 'networking'],
    devopsScenario: 'Verifying private VPC subnet IP assignment on newly provisioned AWS EC2 or Kubernetes nodes.',
  },
  {
    id: 'net-ip-route',
    command: 'ip route',
    title: 'Check Kernel IP Routing Table & Default Gateway',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Outputs the IP routing entries determining which gateway handles outbound packet traffic.',
    difficulty: 'Intermediate',
    tags: ['ip', 'routing', 'gateway'],
    devopsScenario: 'Troubleshooting egress connectivity issues in custom AWS VPC NAT gateway routes.',
  },
  {
    id: 'net-curl-head',
    command: 'curl -I https://api.saivinod.dev/health',
    title: 'Fetch HTTP Response Headers Only',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Performs HTTP HEAD request to inspect status codes (200 OK), content types, and server headers.',
    difficulty: 'Intermediate',
    flags: [{ flag: '-I', desc: 'Show document info and HTTP headers only' }],
    tags: ['curl', 'http', 'api'],
    devopsScenario: 'Probing health endpoints through Application Load Balancers without downloading response body.',
  },
  {
    id: 'net-curl-silent',
    command: 'curl -s https://api.saivinod.dev/metrics',
    title: 'Query Endpoint in Silent Mode',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Suppresses progress meter and error messages for clean script integration.',
    difficulty: 'Beginner',
    flags: [{ flag: '-s', desc: 'Silent mode: don\'t show progress meter or error messages' }],
    tags: ['curl', 'metrics', 'bash'],
  },
  {
    id: 'net-ping',
    command: 'ping -c 3 8.8.8.8',
    title: 'Send ICMP Echo Requests with Count Limit',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Tests ICMP network reachability and round-trip latency to a target host.',
    difficulty: 'Beginner',
    flags: [{ flag: '-c 3', desc: 'Stop after sending 3 packets' }],
    tags: ['ping', 'latency', 'connectivity'],
  },
  {
    id: 'net-resolv',
    command: 'cat /etc/resolv.conf',
    title: 'Inspect Upstream DNS Nameservers',
    category: 'networking',
    categoryTitle: 'Cloud Networking',
    description: 'Reads local DNS resolver configuration file containing nameserver IP addresses.',
    difficulty: 'Beginner',
    tags: ['dns', 'networking', 'resolv'],
    devopsScenario: 'Fixing CoreDNS resolution timeouts in Kubernetes pod network namespaces.',
  },

  // 6. Log Analysis & Text Processing
  {
    id: 'text-grep-err',
    command: 'grep "500" /var/log/nginx/access.log',
    title: 'Filter Access Logs for Internal Server Errors',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Searches log records line-by-line for HTTP 500 status occurrences.',
    difficulty: 'Beginner',
    tags: ['grep', 'logs', 'http'],
    devopsScenario: 'Surfacing error spikes during post-deployment smoke tests.',
  },
  {
    id: 'text-grep-count',
    command: 'grep -c "GET" /var/log/nginx/access.log',
    title: 'Count Matching Log Occurrences',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Suppresses normal output and only prints the count of lines containing the target string.',
    difficulty: 'Beginner',
    flags: [{ flag: '-c', desc: 'Only print a count of selected lines' }],
    tags: ['grep', 'count', 'metrics'],
  },
  {
    id: 'text-awk-cols',
    command: "awk '{print $1, $7}' /var/log/nginx/access.log",
    title: 'Extract IP Address and Requested URI with Awk',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Parses whitespace-delimited columns: $1 (Client IP) and $7 (HTTP Request URI).',
    difficulty: 'Intermediate',
    tags: ['awk', 'parsing', 'logs'],
    devopsScenario: 'Extracting client IP and endpoint pairs for DDoS traffic pattern analysis.',
  },
  {
    id: 'text-cut-fields',
    command: 'cut -d: -f1 /etc/passwd',
    title: 'Extract Usernames from Delimited /etc/passwd',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Splits lines by colon delimiter and extracts the first field (usernames).',
    difficulty: 'Intermediate',
    flags: [
      { flag: '-d:', desc: 'Use colon as delimiter' },
      { flag: '-f1', desc: 'Select only field 1' },
    ],
    tags: ['cut', 'users', 'text'],
  },
  {
    id: 'text-sort-uniq',
    command: "awk '{print $1}' /var/log/nginx/access.log | sort | uniq -c",
    title: 'Calculate Unique IP Request Frequencies',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Extracts IP addresses, sorts them into adjacent groupings, and counts occurrences of each unique IP.',
    difficulty: 'Advanced',
    tags: ['awk', 'sort', 'uniq', 'pipeline'],
    devopsScenario: 'Identifying aggressive scrapers or bots hammering API gateway instances.',
  },
  {
    id: 'text-sed-sub',
    command: "sed 's/500/503/g' /var/log/nginx/access.log | head -n 5",
    title: 'Stream Editor In-line String Substitution',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Applies regular expression search and replace across the text stream.',
    difficulty: 'Intermediate',
    tags: ['sed', 'regex', 'stream'],
  },
  {
    id: 'text-wc-lines',
    command: 'wc -l /var/log/nginx/access.log',
    title: 'Count Total Lines in Log Stream',
    category: 'text',
    categoryTitle: 'Log Analysis & Text Processing',
    description: 'Calculates the newline count of the target file.',
    difficulty: 'Beginner',
    flags: [{ flag: '-l', desc: 'Print newline counts' }],
    tags: ['wc', 'count', 'files'],
  },

  // 7. Storage & Hardware Stats
  {
    id: 'disk-df-h',
    command: 'df -h',
    title: 'Inspect Disk Filesystem Capacity & Mounts',
    category: 'disk',
    categoryTitle: 'Storage & Hardware Stats',
    description: 'Displays disk space usage, available megabytes/gigabytes, and mount points across partitions.',
    difficulty: 'Beginner',
    flags: [{ flag: '-h', desc: 'Human-readable sizes (Powers of 1024: 1K, 234M, 2G)' }],
    tags: ['df', 'disk', 'storage'],
    devopsScenario: 'Diagnosing root volume exhaustion (/dev/root 100% full) causing server crashes.',
  },
  {
    id: 'disk-du-sh',
    command: 'du -sh /var/log/*',
    title: 'Calculate Directory Storage Footprints',
    category: 'disk',
    categoryTitle: 'Storage & Hardware Stats',
    description: 'Summarizes the disk space consumed by each item in /var/log in human-readable format.',
    difficulty: 'Intermediate',
    flags: [
      { flag: '-s', desc: 'Display only a total summary for each argument' },
      { flag: '-h', desc: 'Print sizes in human-readable format' },
    ],
    tags: ['du', 'storage', 'cleanup'],
    devopsScenario: 'Identifying which log directory is causing storage alarms before triggering rotation.',
  },
  {
    id: 'disk-free-m',
    command: 'free -m',
    title: 'Inspect System RAM & Swap Allocation',
    category: 'disk',
    categoryTitle: 'Storage & Hardware Stats',
    description: 'Displays total, used, free, shared, buffer/cache, and available RAM in megabytes.',
    difficulty: 'Beginner',
    flags: [{ flag: '-m', desc: 'Show memory metrics in megabytes' }],
    tags: ['free', 'memory', 'ram'],
    devopsScenario: 'Verifying "available" memory headroom before deploying a high-concurrency JVM or Node service.',
  },

  // 8. Bash Scripting & Pipelines
  {
    id: 'bash-export-var',
    command: 'export APP_ENV=production && echo $APP_ENV',
    title: 'Define and Verify Environment Variable',
    category: 'bash',
    categoryTitle: 'Shell Scripting & Pipelines',
    description: 'Exports an environment variable to child processes and prints its value.',
    difficulty: 'Beginner',
    tags: ['export', 'environment', 'variables'],
  },
  {
    id: 'bash-redirect-write',
    command: 'echo "DEPLOY_TIME=$(date)" > /home/sai/workspace/build.env',
    title: 'Overwrite stdout Stream to Target File',
    category: 'bash',
    categoryTitle: 'Shell Scripting & Pipelines',
    description: 'Redirects standard output to create or overwrite the destination file.',
    difficulty: 'Beginner',
    tags: ['redirect', 'stdout', 'files'],
  },
  {
    id: 'bash-redirect-append',
    command: 'echo "BUILD_ID=10842" >> /home/sai/workspace/build.env',
    title: 'Append stdout Stream Without Overwriting',
    category: 'bash',
    categoryTitle: 'Shell Scripting & Pipelines',
    description: 'Appends data to the end of an existing file using >>.',
    difficulty: 'Beginner',
    tags: ['append', 'redirect', 'files'],
  },
  {
    id: 'bash-exit-code',
    command: 'ls /nonexistent_folder 2> /dev/null; echo $?',
    title: 'Inspect Command Exit Code ($?)',
    category: 'bash',
    categoryTitle: 'Shell Scripting & Pipelines',
    description: 'Demonstrates non-zero exit codes (Exit Code 2 for failure, Exit Code 0 for success).',
    difficulty: 'Intermediate',
    tags: ['exit-code', 'bash', 'error-handling'],
    devopsScenario: 'Implementing conditional bash error handling: `if [ $? -ne 0 ]; then exit 1; fi`.',
  },
  {
    id: 'bash-pipe-wc',
    command: 'ls -la /var/log | wc -l',
    title: 'Pipe Directory Listing to Word Count',
    category: 'bash',
    categoryTitle: 'Shell Scripting & Pipelines',
    description: 'Streams stdout of ls -la into wc -l stdin to count items.',
    difficulty: 'Beginner',
    tags: ['pipe', 'wc', 'listing'],
  },

  // 9. DevOps & Production Incidents
  {
    id: 'devops-tar-create',
    command: 'tar -czvf /home/sai/logs_backup.tar.gz /var/log/nginx',
    title: 'Create Compressed Gzip Tarball of Logs',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Bundles a directory into a tar archive and compresses it with gzip.',
    difficulty: 'Intermediate',
    flags: [
      { flag: '-c', desc: 'Create a new archive' },
      { flag: '-z', desc: 'Filter archive through gzip' },
      { flag: '-v', desc: 'Verbosely list files processed' },
      { flag: '-f', desc: 'Use archive file name' },
    ],
    tags: ['tar', 'backup', 'compression'],
    devopsScenario: 'Archiving rotation logs before transferring them to AWS S3 Glacier buckets.',
  },
  {
    id: 'devops-tar-extract',
    command: 'tar -xzvf /home/sai/logs_backup.tar.gz',
    title: 'Extract Compressed Tarball Archive',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Extracts all contents from a .tar.gz archive into the current directory.',
    difficulty: 'Intermediate',
    flags: [{ flag: '-x', desc: 'Extract files from an archive' }],
    tags: ['tar', 'extract', 'backup'],
  },
  {
    id: 'devops-os-release',
    command: 'cat /etc/os-release',
    title: 'Inspect Operating System Distribution & Codename',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Outputs Linux distribution vendor, version, and codename (e.g. Ubuntu 24.04 LTS Noble Numbat).',
    difficulty: 'Beginner',
    tags: ['os', 'system', 'distro'],
  },
  {
    id: 'devops-hosts',
    command: 'cat /etc/hosts',
    title: 'Inspect Static Hostname to IP Bindings',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Reads local static hostname translation table.',
    difficulty: 'Beginner',
    tags: ['hosts', 'networking', 'dns'],
  },
  {
    id: 'devops-grep-multipattern',
    command: 'grep -E "(404|500)" /var/log/nginx/access.log',
    title: 'Grep Multi-Pattern Extended Regex Search',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Finds log records containing either 404 (Not Found) or 500 (Server Error).',
    difficulty: 'Intermediate',
    flags: [{ flag: '-E', desc: 'Interpret pattern as an Extended Regular Expression (ERE)' }],
    tags: ['grep', 'regex', 'errors'],
  },
  {
    id: 'devops-stat',
    command: 'stat /home/sai/scripts/worker.py',
    title: 'Display Detailed File & Inode Status',
    category: 'devops',
    categoryTitle: 'DevOps & Production Incidents',
    description: 'Outputs exact inode number, block counts, octal permissions, UID/GID, and access/modify timestamps.',
    difficulty: 'Intermediate',
    tags: ['stat', 'inode', 'metadata'],
  },
];
